CREATE TABLE IF NOT EXISTS course (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      course_name VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
                                     username VARCHAR(50) NOT NULL PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
    );

CREATE TABLE IF NOT EXISTS lecture (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       lecture_no INT NOT NULL,
                                       lecture_name VARCHAR(100) NOT NULL,
    course_id BIGINT NOT NULL,
    FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE,
    UNIQUE (course_id, lecture_no)
    );

CREATE TABLE IF NOT EXISTS lecturenotes (
                                            id UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    content BYTEA NOT NULL,
    uploaded_by VARCHAR(50) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lecture_id BIGINT NOT NULL,
    FOREIGN KEY (lecture_id) REFERENCES lecture(id) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(username)
    );

CREATE TABLE IF NOT EXISTS poll (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    question VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    course_id BIGINT NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(username)
    );


CREATE TABLE IF NOT EXISTS poll_option (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           text VARCHAR(255) NOT NULL,
    vote_count INT NOT NULL DEFAULT 0,
    poll_id BIGINT NOT NULL,
    FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS poll_vote (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         selected_option_id BIGINT NOT NULL,
                                         username VARCHAR(50) NOT NULL,
    poll_id BIGINT NOT NULL,
    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (selected_option_id) REFERENCES poll_option(id),
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (poll_id) REFERENCES poll(id),
    UNIQUE (username, poll_id)
    );

CREATE TABLE  IF NOT EXISTS course_comments (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 content TEXT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 author_username VARCHAR(50) NOT NULL,
                                 course_id BIGINT NOT NULL,
                                 FOREIGN KEY (author_username) REFERENCES users(username),
                                 FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  poll_comments (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               content TEXT NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               author_username VARCHAR(50) NOT NULL,
                               poll_id BIGINT NOT NULL,
                               FOREIGN KEY (author_username) REFERENCES users(username),
                               FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lecture_comments (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                content TEXT NOT NULL,
                                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                author_username VARCHAR(50) NOT NULL,
    lecture_id BIGINT NOT NULL,
    FOREIGN KEY (author_username) REFERENCES users(username),
    FOREIGN KEY (lecture_id) REFERENCES lecture(id) ON DELETE CASCADE);